# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pictures", type: :request do
  let(:file_content_type) { "image/jpeg" }
  let(:file_path) { "spec/support/macbookair_stickered.jpg" }
  let(:file) { Rack::Test::UploadedFile.new(file_path, file_content_type) }
  let(:name) { "#{Faker::Address.community}, #{Faker::Address.city}" }
  let(:date) { Time.zone.today.iso8601 }

  # This should return the minimal set of attributes required to create a valid
  # Picture. As you add validations to Picture, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { file: file, date: Time.zone.today, name: name }
  }

  let(:invalid_attributes) {
    { file: nil, date: Time.zone.today, name: name }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Picture.create! valid_attributes
      get pictures_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      picture = Picture.create! valid_attributes
      get picture_url(picture.urlsafe_id)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_picture_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      picture = Picture.create! valid_attributes
      get edit_picture_url(picture.urlsafe_id)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Picture" do
        expect {
          post pictures_url, params: { picture: valid_attributes }
        }.to change { Picture.count }.by(1)
      end

      it "redirects to the created picture" do
        post pictures_url, params: { picture: valid_attributes }
        expect(response).to redirect_to(picture_url(Picture.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Picture" do
        expect {
          post pictures_url, params: { picture: invalid_attributes }
        }.to change { Picture.count }.by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post pictures_url, params: { picture: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: "New Name" } # TODO: test to replace file
      }

      it "updates the requested picture" do
        picture = Picture.create! valid_attributes
        patch picture_url(picture.urlsafe_id), params: { picture: new_attributes }
        picture.reload
        expect(picture.name).to eq("New Name")
      end

      it "redirects to the picture" do
        picture = Picture.create! valid_attributes
        patch picture_url(picture.urlsafe_id), params: { picture: new_attributes }
        picture.reload
        expect(response).to redirect_to(picture_url(picture.urlsafe_id))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        picture = Picture.create! valid_attributes
        patch picture_url(picture.urlsafe_id), params: { picture: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested picture" do
      picture = Picture.create! valid_attributes
      expect {
        delete picture_url(picture.urlsafe_id)
      }.to change { Picture.count }.by(-1)
    end

    it "redirects to the pictures list" do
      picture = Picture.create! valid_attributes
      delete picture_url(picture.urlsafe_id)
      expect(response).to redirect_to(pictures_url)
    end
  end
end
