# frozen_string_literal: true

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/current_team/locations", type: :request do
  let!(:member) { Member.create!(team: team, user: user, roles: Array(roles.sample)) }

  let(:team) { FactoryBot.create(:team) }
  let(:user) { FactoryBot.create(:user) }
  let(:roles) { %i[owner manager editor] }

  let(:valid_attributes) { { name: "Camping spot near the beach", country_code: "de", url: "www.yournaling.com", team: } }
  let(:invalid_attributes) { { name: nil } }

  before do
    sign_in(user)
    switch_current_team(team)
  end

  describe "GET /index" do
    it "renders a successful response" do
      Location.create! valid_attributes

      get current_team_locations_url

      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response with header metadata and controls" do
      location = Location.create! valid_attributes

      get current_team_location_url(location)

      expect(response).to be_successful
      expect(response.body).to include("Visibility:")
      expect(response.body).to include("Rewrite")
    end
  end

  describe "GET /new" do
    it "renders the location form with its fields" do
      get new_current_team_location_url

      expect(response).to be_successful
      assert_select "form[action=?][method=?]", current_team_locations_path, "post" do
        assert_select "input[name=?]", "location[name]"
        assert_select "select[name=?]", "location[country_code]"
        assert_select "input[name=?]", "location[address]"
        assert_select "input[name=?]", "location[lat]"
        assert_select "input[name=?]", "location[long]"
        assert_select "input[name=?]", "location[url]"
        assert_select "textarea[name=?]", "location[description]"
      end
    end
  end

  describe "GET /edit" do
    it "renders the location form with its fields" do
      location = Location.create! valid_attributes

      get edit_current_team_location_url(location)

      expect(response).to be_successful
      assert_select "form[action=?][method=?]", current_team_location_path(location), "post" do
        assert_select "input[name=?]", "location[name]"
        assert_select "select[name=?]", "location[country_code]"
        assert_select "input[name=?]", "location[address]"
        assert_select "input[name=?]", "location[lat]"
        assert_select "input[name=?]", "location[long]"
        assert_select "input[name=?]", "location[url]"
        assert_select "textarea[name=?]", "location[description]"
      end
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Location" do
        expect {
          post current_team_locations_url, params: { location: valid_attributes }
        }.to change { Location.count }.by(1)
      end

      it "redirects to the created location" do
        post current_team_locations_url, params: { location: valid_attributes }
        expect(response).to redirect_to(current_team_location_url(Location.first))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Location" do
        expect {
          post current_team_locations_url, params: { location: invalid_attributes }
        }.to change { Location.count }.by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post current_team_locations_url, params: { location: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end

    context "with JSON format" do
      it "creates a location and returns JSON response" do
        post current_team_locations_url(format: :json), params: { location: valid_attributes }
        expect(response).to have_http_status(:created)
        json = response.parsed_body
        expect(json["name"]).to eq("Camping spot near the beach")
        expect(json["country_code"]).to eq("de")
      end

      it "returns 422 with errors array when invalid" do
        post current_team_locations_url(format: :json), params: { location: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
        json = response.parsed_body
        expect(json["errors"]).to be_present
      end
    end

    context "when member has unauthorized role (publisher)" do
      before { member.update!(roles: %w[publisher]) }

      it "forbids creating a location with 403 Forbidden" do
        post current_team_locations_url, params: { location: valid_attributes }
        expect(response).to have_http_status(:forbidden)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) { { url: "www.rantanvan.com" } }

      it "updates the requested location" do
        location = Location.create! valid_attributes

        patch current_team_location_url(location), params: { location: new_attributes }

        location.reload
        expect(location.url).to eq("https://www.rantanvan.com")
      end

      it "redirects to the location" do
        location = Location.create! valid_attributes

        patch current_team_location_url(location), params: { location: new_attributes }

        location.reload
        expect(response).to redirect_to(current_team_location_url(location))
      end
    end

    context "with invalid parameters" do
      let(:new_attributes) { { url: "www.rantanvan.com" } }

      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        location = Location.create! valid_attributes
        patch current_team_location_url(location), params: { location: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end

    context "when member has unauthorized role (publisher)" do
      let(:new_attributes) { { url: "www.rantanvan.com" } }

      before { member.update!(roles: %w[publisher]) }

      it "forbids updating a location with 403 Forbidden" do
        location = Location.create! valid_attributes
        patch current_team_location_url(location), params: { location: new_attributes }

        expect(response).to have_http_status(:forbidden)
      end
    end
  end

  describe "DELETE /destroy" do
    let(:roles) { %i[owner manager] }
    let!(:location) { Location.create! valid_attributes }

    it "destroys the requested location" do
      expect {
        delete current_team_location_url(location)
      }.to change { Location.count }.by(-1)
    end

    it "redirects to the locations list" do
      delete current_team_location_url(location)

      expect(response).to redirect_to(current_team_locations_url)
    end

    it "prevents deleting a location that is referenced by a memory or chronicle" do
      FactoryBot.create(:memory, team: team, location: location)

      expect {
        delete current_team_location_url(location)
      }.not_to(change { Location.count })

      expect(response).to redirect_to(edit_current_team_location_url(location))
      expect(flash[:alert]).to be_present
    end

    context "when member has unauthorized role (editor)" do
      before { member.update!(roles: %w[editor]) }

      it "forbids deleting a location with 403 Forbidden" do
        delete current_team_location_url(location)

        expect(response).to have_http_status(:forbidden)
      end
    end
  end
end
