# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/current_team/memories", type: :request do
  let!(:member) { Member.create!(team: team, user: user, roles: Array(roles.sample)) }

  let(:user) { FactoryBot.create(:user) }
  let(:team) { FactoryBot.create(:team) }
  let(:weblink) { FactoryBot.create(:weblink, team:) }
  let(:roles) { %i[owner manager editor] }

  let(:valid_attributes) { { team_id: team.id, memo: "Memo Text", weblink: } }
  let(:invalid_attributes) { { team_id: team.id, memo: "." } }

  before do
    sign_in(user)
    switch_current_team(team)
  end

  describe "GET /index" do
    let!(:memory) { Memory.create! valid_attributes }

    context "when no current_team has been selected" do
      before do
        go_solo(team)
      end

      it "forbids access and redirects to home path" do
        get current_team_memories_url
        expect(response).to redirect_to(root_url)
      end
    end

    context "when the same current_team has been selected already" do
      it "renders a successful response" do
        get current_team_memories_url
        expect(response).to be_successful
      end
    end
  end

  describe "GET /show" do
    let!(:memory) { Memory.create! valid_attributes }

    it "renders a successful response" do
      get current_team_memory_url(memory.urlsafe_id)
      expect(response).to be_successful
    end

    it "renders a working 'Change visibility' button linking to edit visibility form (regression test)" do
      get current_team_memory_url(memory.urlsafe_id)
      expect(response).to be_successful
      expect(response.body).to include("Change visibility")

      visibility_link_path = current_team_edit_content_visibility_path(memory)
      expect(response.body).to include(visibility_link_path)

      get visibility_link_path
      expect(response).to be_successful
      expect(response.body).to include("Edit content visibility")
    end

    it "renders all attached insights (picture, thought, location, weblink) (regression test)" do
      thought = FactoryBot.create(:thought, team: team, text: "Philosophical thought")
      location = FactoryBot.create(:location, team: team, name: "Alhambra Palace")
      picture = FactoryBot.create(:picture, team: team, name: "Granada View")
      memory = Memory.create!(valid_attributes.merge(thought: thought, location: location, picture: picture))

      get current_team_memory_url(memory.urlsafe_id)
      expect(response).to be_successful
      expect(response.body).to include(memory.memo)
      expect(response.body).to include("Philosophical thought")
      expect(response.body).to include("Alhambra Palace")
      expect(response.body).to include("Granada View")
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_current_team_memory_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    let!(:memory) { Memory.create! valid_attributes }

    it "renders a successful response" do
      get edit_current_team_memory_url(memory.urlsafe_id)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Memory" do
        expect {
          post current_team_memories_url, params: { memory: valid_attributes }
        }.to change { Memory.count }.by(1)
      end

      it "redirects to the created memory" do
        post current_team_memories_url, params: { memory: valid_attributes }

        expect(response).to redirect_to(current_team_memory_url(Memory.first.urlsafe_id))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Memory" do
        expect {
          post current_team_memories_url, params: { memory: invalid_attributes }
        }.to change { Memory.count }.by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post current_team_memories_url, params: { memory: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end

    context "with insight attachments and picture uploads" do
      let(:uploaded_file) do
        Rack::Test::UploadedFile.new(
          Rails.root.join("spec/support/macbookair_stickered.jpg"),
          "image/jpeg"
        )
      end

      it "creates a memory and uploads a new picture in the same request" do
        params = {
          memo: "Morning surf session",
          picture_file: uploaded_file,
          picture_name: "Morning Wave",
        }

        expect {
          post current_team_memories_url, params: { memory: params }
        }.to change { Memory.count }.by(1)
          .and change { Picture.count }.by(1)

        memory = Memory.last
        expect(memory.picture).to be_present
        expect(memory.picture.name).to eq("Morning Wave")
      end

      it "creates a memory with inline location, thought, and weblink" do
        params = {
          memo: "Complete memory trip",
          location_name: "Mount Olympus",
          location_address: "Thessaly, Greece",
          location_country_code: "gr",
          thought_text: "A beautiful view from the summit",
          weblink_name: "Mountain Guide",
          weblink_url: "https://olympus-guide.example.com",
        }

        expect {
          post current_team_memories_url, params: { memory: params }
        }.to change { Memory.count }.by(1)
          .and change { Location.count }.by(1)
          .and change { Thought.count }.by(1)
          .and change { Weblink.count }.by(1)

        memory = Memory.last
        expect(memory.location.name).to eq("Mount Olympus")
        expect(memory.thought.text).to eq("A beautiful view from the summit")
        expect(memory.weblink.name).to eq("Mountain Guide")
      end

      it "renders 422 when inline location fails validation and rolls back memory creation" do
        params = {
          memo: "Memory with bad location",
          location_name: "Invalid Country Place",
          location_country_code: "invalid_cc",
        }

        expect {
          post current_team_memories_url, params: { memory: params }
        }.not_to(change { Memory.count })

        expect(Location.where(name: "Invalid Country Place")).not_to exist
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.body).to include("Location")
      end

      it "renders 422 and retains form values when creating memory with picture upload and invalid location" do
        FactoryBot.create(:location, team: team, name: "Existing Location")
        params = {
          memo: "Memory with picture and duplicate location",
          picture_file: uploaded_file,
          picture_name: "My Photo",
          location_name: "Existing Location",
          location_country_code: "de",
          location_address: "123 Main St",
        }

        expect {
          post current_team_memories_url, params: { memory: params }
        }.not_to(change { Memory.count })

        expect(response).to have_http_status(:unprocessable_content)
        expect(response.body).to include("Location")
        expect(response.body).to include("Existing Location")
        expect(response.body).to include("123 Main St")
        expect(response.body).to include("My Photo")
      end

      it "renders 422 when both existing insight ID and new creation parameters are submitted (Option C)" do
        existing_picture = FactoryBot.create(:picture, team: team)
        params = {
          memo: "Conflicting picture parameters",
          picture_id: existing_picture.id,
          picture_file: uploaded_file,
        }

        expect {
          post current_team_memories_url, params: { memory: params }
        }.not_to(change { Memory.count })

        expect(response).to have_http_status(:unprocessable_content)
        expect(response.body).to include("Please either select an existing picture or upload a new picture, not both")
      end
    end

    context "when member has unauthorized role (publisher)" do
      before { member.update!(roles: %w[publisher]) }

      it "forbids creating a memory with 403 Forbidden" do
        post current_team_memories_url, params: { memory: valid_attributes }

        expect(response).to have_http_status(:forbidden)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:location) { FactoryBot.create(:location, team: team) }
      let(:new_attributes) { { location_id: location.id } }

      it "updates the requested memory" do
        memory = Memory.create! valid_attributes

        patch current_team_memory_url(memory), params: { memory: new_attributes }

        memory.reload
        expect(memory.location_id).to eq(location.id)
      end

      it "redirects to the memory" do
        memory = Memory.create! valid_attributes

        patch current_team_memory_url(memory), params: { memory: new_attributes }

        memory.reload
        expect(response).to redirect_to(current_team_memory_url(memory))
      end
    end

    context "with new inline insight attachments on update" do
      it "creates and attaches a new thought on update" do
        memory = Memory.create! valid_attributes

        expect {
          patch current_team_memory_url(memory), params: { memory: { thought_text: "Updated reflection" } }
        }.to change { Thought.count }.by(1)

        expect(memory.reload.thought.text).to eq("Updated reflection")
      end

      it "renders 422 and rolls back when new insight fails validation on update" do
        memory = Memory.create! valid_attributes

        patch current_team_memory_url(memory), params: { memory: { thought_text: "a" * 2000 } }

        expect(response).to have_http_status(:unprocessable_content)
        expect(memory.reload.thought).to be_nil
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        memory = Memory.create! valid_attributes
        patch current_team_memory_url(memory), params: { memory: invalid_attributes }

        expect(response).to have_http_status(:unprocessable_content)
      end

      it "renders 422 when clearing memo to blank text (regression test for compact_blank bug)" do
        memory = Memory.create!(team: team, memo: "Original long memo", visibility: "internal")

        patch current_team_memory_url(memory), params: { memory: { memo: "" } }

        expect(response).to have_http_status(:unprocessable_content)
        expect(memory.reload.memo).to eq("Original long memo")
      end
    end

    context "when detaching insights on update" do
      it "detaches attached insights when blank IDs are submitted" do
        loc = FactoryBot.create(:location, team: team)
        thot = FactoryBot.create(:thought, team: team)
        pic = FactoryBot.create(:picture, team: team)
        web = FactoryBot.create(:weblink, team: team)
        memory = Memory.create!(team: team, memo: "Memory with all insights", location: loc, thought: thot, picture: pic,
          weblink: web, visibility: "internal")

        patch current_team_memory_url(memory), params: {
          memory: {
            picture_id: "",
            location_id: "",
            thought_id: "",
            weblink_id: "",
          },
        }

        expect(response).to redirect_to(current_team_memory_url(memory))
        memory.reload
        expect(memory.picture).to be_nil
        expect(memory.location).to be_nil
        expect(memory.thought).to be_nil
        expect(memory.weblink).to be_nil
      end
    end

    context "when member has unauthorized role (publisher)" do
      let(:location) { FactoryBot.create(:location, team: team) }
      let(:new_attributes) { { location_id: location.id } }

      before { member.update!(roles: %w[publisher]) }

      it "forbids updating a memory with 403 Forbidden" do
        memory = Memory.create! valid_attributes
        patch current_team_memory_url(memory), params: { memory: new_attributes }

        expect(response).to have_http_status(:forbidden)
      end
    end
  end

  describe "DELETE /destroy" do
    let(:roles) { %i[owner manager] }

    let!(:memory) { Memory.create! valid_attributes }

    it "destroys the requested memory" do
      expect {
        delete current_team_memory_url(memory)
      }.to change { Memory.count }.by(-1)
    end

    it "redirects to the memories list" do
      delete current_team_memory_url(memory)

      expect(response).to redirect_to(current_team_memories_url)
    end

    context "when member has unauthorized role (editor)" do
      before { member.update!(roles: %w[editor]) }

      it "forbids deleting a memory with 403 Forbidden" do
        delete current_team_memory_url(memory)

        expect(response).to have_http_status(:forbidden)
      end
    end
  end
end
