# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/current_team/pictures", type: :request do
  let!(:member) { Member.create!(team: team, user: user, roles: Array(roles.sample)) }

  let(:file_content_type) { "image/jpeg" }
  let(:file_path) { "spec/support/macbookair_stickered.jpg" }
  let(:file) { Rack::Test::UploadedFile.new(file_path, file_content_type) }
  let(:name) { "#{Faker::Address.community}, #{Faker::Address.city}" }
  let(:date) { Time.zone.today.iso8601 }
  let(:team) { FactoryBot.create(:team) }
  let(:user) { FactoryBot.create(:user) }
  let(:roles) { %i[owner manager editor] }
  let(:valid_attributes) { { file: file, date: Time.zone.today, name: name, team: team } }
  let(:invalid_attributes) { { file: nil, date: Time.zone.today, name: nil, team: team } }

  before do
    sign_in(user)
    switch_current_team(team)
  end

  describe "GET /index" do
    it "renders a successful response" do
      Picture.create! valid_attributes

      get current_team_pictures_url

      expect(response).to be_successful
      expect(response.body).to match(/#{name}/)
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      picture = Picture.create! valid_attributes

      get current_team_picture_url(picture.urlsafe_id)

      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_current_team_picture_url

      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      picture = Picture.create! valid_attributes

      get edit_current_team_picture_url(picture.urlsafe_id)

      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Picture and redirects to the created picture" do
        expect {
          post current_team_pictures_url, params: { picture: valid_attributes }
        }.to change { Picture.count }.by(1)

        expect(response).to redirect_to(current_team_picture_url(Picture.first))
      end

      it "creates a new Picture and records the event" do
        expect {
          post current_team_pictures_url, params: { picture: valid_attributes }
        }.to change { RecordEvent.count }.by(1)

        event = RecordEvent.first
        expect(event.name).to eq("created")
        expect(event.record_type).to eq("pic")
        expect(event.record_id).to eq(Picture.first.id)
        expect(event.team_id).to eq(team.id)
        expect(event.user_id).to eq(user.id)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Picture" do
        expect {
          post current_team_pictures_url, params: { picture: invalid_attributes }
        }.to change { Picture.count }.by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post current_team_pictures_url, params: { picture: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end

    context "with JSON format" do
      it "creates a picture and returns JSON response" do
        post current_team_pictures_url(format: :json), params: { picture: valid_attributes }
        expect(response).to have_http_status(:created)
        json = response.parsed_body
        expect(json["id"]).to be_present
        expect(json["name"]).to be_present
        expect(json["type"]).to eq("picture")
      end

      it "returns 422 with errors array when file is invalid" do
        post current_team_pictures_url(format: :json), params: { picture: { name: "Missing file" } }
        expect(response).to have_http_status(:unprocessable_content)
        json = response.parsed_body
        expect(json["errors"]).to be_present
      end
    end

    context "when member has unauthorized role (publisher)" do
      before { member.update!(roles: %w[publisher]) }

      it "forbids creating a picture with 403 Forbidden" do
        post current_team_pictures_url, params: { picture: valid_attributes }
        expect(response).to have_http_status(:forbidden)
      end
    end
  end

  describe "PATCH /update" do
    let(:picture) { Picture.create! valid_attributes }

    context "with valid parameters" do
      let(:new_attributes) { { name: "New Name" } }

      it "updates the requested picture and redirects to the picture" do
        patch current_team_picture_url(picture.urlsafe_id), params: { picture: new_attributes }

        picture.reload

        expect(picture.name).to eq("New Name")
        expect(response).to redirect_to(current_team_picture_url(picture.urlsafe_id))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        patch current_team_picture_url(picture.urlsafe_id), params: { picture: invalid_attributes }

        expect(response).to have_http_status(:unprocessable_content)
      end
    end

    context "when member has unauthorized role (publisher)" do
      let(:new_attributes) { { name: "New Name" } }

      before { member.update!(roles: %w[publisher]) }

      it "forbids updating a picture with 403 Forbidden" do
        patch current_team_picture_url(picture.urlsafe_id), params: { picture: new_attributes }
        expect(response).to have_http_status(:forbidden)
      end
    end
  end

  describe "DELETE /destroy" do
    let(:picture) { Picture.create! valid_attributes }
    let(:roles) { %i[owner manager] }

    it "destroys the requested picture and redirects to the pictures list" do
      picture # to create it
      expect(Picture.count).to eq(1)

      delete current_team_picture_url(picture.urlsafe_id)

      expect(Picture.count).to eq(0)
      expect(response).to redirect_to(current_team_pictures_url)
    end

    it "deletes a Picture and records the event" do
      picture # to create it
      expect(Picture.count).to eq(1)

      delete current_team_picture_url(picture.urlsafe_id)

      expect(RecordEvent.count).to eq(1)

      event = RecordEvent.first
      expect(event.name).to eq("deleted")
      expect(event.record_type).to eq("pic")
      expect(event.record_id).to eq(picture.id)
      expect(event.team_id).to eq(team.id)
      expect(event.user_id).to eq(user.id)
    end

    it "prevents deleting a picture that is referenced by a memory or chronicle" do
      FactoryBot.create(:memory, team: team, picture: picture)

      expect {
        delete current_team_picture_url(picture.urlsafe_id)
      }.not_to(change { Picture.count })

      expect(response).to redirect_to(edit_current_team_picture_url(picture.urlsafe_id))
      expect(flash[:alert]).to be_present
    end

    context "when member has unauthorized role (editor)" do
      before { member.update!(roles: %w[editor]) }

      it "forbids deleting a picture with 403 Forbidden" do
        delete current_team_picture_url(picture.urlsafe_id)
        expect(response).to have_http_status(:forbidden)
      end
    end
  end
end
