# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/current_team/weblinks", type: :request do
  let!(:member) { Member.create!(team: team, user: user, roles: Array(roles.sample)) }

  let(:team) { FactoryBot.create(:team) }
  let(:user) { FactoryBot.create(:user) }
  let(:roles) { %i[owner manager editor] }

  let(:valid_attributes) { { name: "Yournaling", url: "www.yournaling.com", description: "Your Journaling", team: } }
  let(:invalid_attributes) { { name: nil } }

  before do
    sign_in(user)
    switch_current_team(team)
  end

  describe "GET /index" do
    it "renders a successful response" do
      Weblink.create! valid_attributes
      get current_team_weblinks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response with header metadata and controls" do
      weblink = Weblink.create! valid_attributes
      get current_team_weblink_url(weblink)
      expect(response).to be_successful
      expect(response.body).to include("Visibility:")
      expect(response.body).to include("Rewrite")
    end
  end

  describe "GET /new" do
    it "renders the form with the weblink fields" do
      get new_current_team_weblink_url

      expect(response).to be_successful
      assert_select "form[action=?][method=?]", current_team_weblinks_path, "post" do
        assert_select "input[name=?]", "weblink[name]"
        assert_select "input[name=?]", "weblink[url]"
        assert_select "textarea[name=?]", "weblink[description]"
      end
    end
  end

  describe "GET /edit" do
    it "renders the form with the weblink fields" do
      weblink = Weblink.create! valid_attributes

      get edit_current_team_weblink_url(weblink)

      expect(response).to be_successful
      assert_select "form[action=?][method=?]", current_team_weblink_path(weblink), "post" do
        assert_select "input[name=?]", "weblink[name]"
        assert_select "input[name=?]", "weblink[url]"
        assert_select "textarea[name=?]", "weblink[description]"
      end
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Weblink" do
        expect {
          post current_team_weblinks_url, params: { weblink: valid_attributes }
        }.to change { Weblink.count }.by(1)
      end

      it "redirects to the created weblink" do
        post current_team_weblinks_url, params: { weblink: valid_attributes }
        expect(response).to redirect_to(current_team_weblink_url(Weblink.first))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Weblink" do
        expect {
          post current_team_weblinks_url, params: { weblink: invalid_attributes }
        }.to change { Weblink.count }.by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post current_team_weblinks_url, params: { weblink: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end

    context "with JSON format" do
      it "creates a weblink and returns JSON response" do
        post current_team_weblinks_url(format: :json), params: { weblink: valid_attributes }
        expect(response).to have_http_status(:created)
        json = response.parsed_body
        expect(json["id"]).to be_present
        expect(json["name"]).to eq(valid_attributes[:name])
        expect(json["type"]).to eq("weblink")
      end

      it "returns 422 with errors array when invalid" do
        post current_team_weblinks_url(format: :json), params: { weblink: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
        json = response.parsed_body
        expect(json["errors"]).to be_present
      end
    end

    context "when member has unauthorized role (publisher)" do
      before { member.update!(roles: %w[publisher]) }

      it "forbids creating a weblink with 403 Forbidden" do
        post current_team_weblinks_url, params: { weblink: valid_attributes }
        expect(response).to have_http_status(:forbidden)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) { { name: "Updated Yournaling Link" } }

      it "updates the requested weblink" do
        weblink = Weblink.create! valid_attributes
        patch current_team_weblink_url(weblink), params: { weblink: new_attributes }
        weblink.reload
        expect(weblink.name).to eq("Updated Yournaling Link")
      end

      it "redirects to the weblink" do
        weblink = Weblink.create! valid_attributes
        patch current_team_weblink_url(weblink), params: { weblink: new_attributes }
        weblink.reload
        expect(response).to redirect_to(current_team_weblink_url(weblink))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        weblink = Weblink.create! valid_attributes
        patch current_team_weblink_url(weblink), params: { weblink: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end

    context "when member has unauthorized role (publisher)" do
      before { member.update!(roles: %w[publisher]) }

      it "forbids updating a weblink with 403 Forbidden" do
        weblink = Weblink.create! valid_attributes
        patch current_team_weblink_url(weblink), params: { weblink: valid_attributes }

        expect(response).to have_http_status(:forbidden)
      end
    end
  end

  describe "DELETE /destroy" do
    let(:roles) { %i[owner manager] }

    it "destroys the requested weblink" do
      weblink = Weblink.create! valid_attributes
      expect {
        delete current_team_weblink_url(weblink)
      }.to change { Weblink.count }.by(-1)
    end

    it "redirects to the weblinks list" do
      weblink = Weblink.create! valid_attributes
      delete current_team_weblink_url(weblink)
      expect(response).to redirect_to(current_team_weblinks_url)
    end

    it "prevents deleting a weblink that is referenced by a memory or chronicle" do
      weblink = Weblink.create! valid_attributes
      FactoryBot.create(:memory, team: team, weblink: weblink)

      expect {
        delete current_team_weblink_url(weblink)
      }.not_to(change { Weblink.count })

      expect(response).to redirect_to(edit_current_team_weblink_url(weblink))
      expect(flash[:alert]).to be_present
    end

    context "when member has unauthorized role (editor)" do
      before { member.update!(roles: %w[editor]) }

      it "forbids deleting a weblink with 403 Forbidden" do
        weblink = Weblink.create! valid_attributes
        delete current_team_weblink_url(weblink)

        expect(response).to have_http_status(:forbidden)
      end
    end
  end
end
